name: CI/CD Pipeline for OpenTelemetry Demo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install docker-compose

    - name: Authenticate Docker with AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Docker Image with Docker Compose
      run: |
        docker-compose build
        docker-compose push

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: eks-actions/eks-kubectl-action@v1
      with:
        cluster-name: otel-demo-cluster
        region: us-east-1
        kubeconfig: ${{ secrets.KUBECONFIG }}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl set image deployment/otel-demo-app otel-demo-app=123456789012.dkr.ecr.us-east-1.amazonaws.com/otel-demo-repo:$GITHUB_SHA
        kubectl rollout status deployment/otel-demo-app

  rollback:
    runs-on: ubuntu-latest
    if: failure()
    needs: deploy

    steps:
    - name: Rollback to previous stable version
      run: |
        kubectl rollout undo deployment/otel-demo-app
